### ISSUE TITLE
Crunchyroll PS4 dump

### ISSUE THREAD

**Issue by SilverStone391** [gameblabla/crunchyroll_ps3_dumps#2]
Hi @gameblabla sorry this may be slightly off topic but would you happen to have Crunchyroll dump for PS4?

**Comment by gameblabla** [comment]
Unfortunately no, i don't. That said, the dumps i have for this PS3 version applies also to the older PS4 version (besides i got it briefly working with the ps4 key until they renewed it). Just not the newer one that had a complete revamp. It's outside the focus of this repo unfortunately. In anycase, if you do want to make your own dumps, its not too late for that version.

**Comment by SilverStone391** [comment]
Hey thanks for the response, so this still works for the old version of the
PS4 crunchyroll, before they redesigned it? are you able do a version for
the old PS4 crunchyroll before they revamped it coincidentally I prefer the
old user interface it shared the same interface as PS3. I’m new to the
scene and don’t know the workings of this stuff, sorry.

**Comment by SilverStone391** [comment]
Looks like this.
